apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: zoneminder
  namespace: zoneminder
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`zm.roonaldo.org`)
      priority: 10
      services:
        - name: zoneminder
          port: 80
    - kind: Rule
      match: Host(`zm.roonaldo.org`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: zoneminder
          port: 80
          scheme: h2c
  tls:
    secretName: zm-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zm-cert
  namespace: zoneminder
spec:
  secretName: zm-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - zm.roonaldo.org
