apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoneminder
  namespace: zoneminder
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        octopusexport: OctopusExport
    spec:
      hostNetwork: true
      volumes:
        - name: zm-pvc
          persistentVolumeClaim:
            claimName: zm-pvc
        - name: cache-volume
          emptyDir:
            medium: Memory
      containers:
        - name: zoneminder
          image: dlandon/zoneminder
          ports:
            - name: zm-port
              containerPort: 9000
            - name: https
              containerPort: 8443
              protocol: TCP
          env:
            - name: TZ
              value: America/Chicago
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: INSTALL_HOOK
              value: "0"
            - name: INSTALL_FACE
              value: "0"
            - name: NSTALL_TINY_YOLOV3
              value: "0"
            - name: PGID
              value: "100"
            - name: INSTALL_YOLOV3
              value: "0"
            - name: INSTALL_YOLOV4
              value: "0"
            - name: MULTI_PORT_START
              value: "0"
            - name: MULTI_PORT_END
              value: "0"
          volumeMounts:
            - name: cache-volume
              mountPath: /dev/shm
              subPath: ""
            - name: zm-pvc
              mountPath: /config
              subPath: ""
            - name: zm-pvc
              mountPath: /var/cache/zoneminder
              subPath: ""
          resources:
            requests:
              memory: 4Gi
              cpu: "1"
            limits:
              memory: 8Gi
              cpu: "2"
