apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoneminder
  labels:
    app: zoneminder
  namespace: zoneminder
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zoneminder
        octopusexport: OctopusExport
    spec:
      # hostNetwork: true
      volumes:
        - name: zm-pvc
          persistentVolumeClaim:
            claimName: zm-pvc
        - name: cache-volume
          emptyDir:
            medium: Memory
      containers:
        - name: zoneminder
          image: "dlandon/zoneminder:latest"
          ports:
            - name: zm-port
              containerPort: 9000
              protocol: TCP
            - name: https
              containerPort: 443
              protocol: TCP
          env:
            - name: TZ
              value: America/Chicago
            - name: PUID
              value: "99"
            - name: PGID
              value: "100"
            - name: INSTALL_HOOK
              value: "0"
            - name: INSTALL_FACE
              value: "0"
            - name: NSTALL_TINY_YOLOV3
              value: "0"
            - name: PGID
              value: "100"
            - name: INSTALL_YOLOV3
              value: "0"
            - name: INSTALL_YOLOV4
              value: "0"
            - name: MULTI_PORT_START
              value: "0"
            - name: MULTI_PORT_END
              value: "0"
          volumeMounts:
            - name: cache-volume
              mountPath: /dev/shm
              subPath: ""
            - name: zm-pvc
              mountPath: /config
              subPath: ""
            - name: zm-pvc
              mountPath: /var/cache/zoneminder
              subPath: ""
          resources:
            requests:
              memory: 4Gi
              cpu: "1"
            limits:
              memory: 8Gi
              cpu: "2"

---
apiVersion: v1
kind: Service
metadata:
  name: zoneminder
  namespace: zoneminder
spec:
  selector:
    app: zoneminder

  type: ClusterIP
  ports:
    - name: https
      port: 443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zomeminder-ingress
  namespace: zoneminder
spec:
  rules:
    - host: "zm.roonaldo.org"
      http:
        paths:
          - pathType: Prefix
            path: "/zm"
            backend:
              service:
                name: zoneminder
                port:
                  number: 443

  tls:
    - hosts:
        - zm.roonaldo.org
      secretName: zm-tls-secret
