apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: pdirectory-server
  namespace: pinglab
spec:
  entryPoints:
    - ldaps
  routes:
    - kind: Rule
      match: Host(`pingdirectory.pd.roonaldo.org`)
      priority: 10
      services:
        - name: pingdirectory-server
          port: 1636
    - kind: Rule
      match: Host(`pingdirectory.pd.roonaldo.org`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: pingdirectory-server
          port: 1636
          scheme: h2c
  tls:
    secretName: pdirectory-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pdirectory-cert
  namespace: pinglab
spec:
  secretName: pdirectory-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - pingdirectory.pd.roonaldo.org
