---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

title: "Noor-Sandstorm Dashboard"
subtitle: "Homer"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false
# footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"

# Optional message
message:
  #url: https://b4bz.io
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Life as a techie"
  icon: "fa fa-grin"
  content: "Welcome to Noor's tech goodies."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Contribute"
    icon: "fab fa-github"
    url: "https://github.com/bastienwirtz/homer"
    target: "_blank" # optional html a tag target attribute
  - name: "Wiki"
    icon: "fas fa-book"
    url: "https://www.wikipedia.org/"
  # this will link to a second homer page that will load config from additional-page.yml and keep default config values as in config.yml file
  # see url field and assets/additional-page.yml.dist used in this example:
  #- name: "another page!"
  #  icon: "fas fa-file-alt"
  #  url: "#additional-page"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  #Kubernetes services
  - name: "Kubernetes"
    logo: "assets/tools/png/kubernetes-dashboard.png"
    items:
      - name: "K-Gui"
        logo: "assets/tools/png/rancher.png"
        subtitle: "Bookmark example"
        tag: "kubernetes"
        keywords: "Rancher Kubernetes Dashboard"
        url: "https://kgui.sandstorm.iot/"
        target: "_blank" # optional html a tag target attribute
      - name: "Argo-CD"
        logo: "assets/tools/png/argocd.png"
        subtitle: "Argo-CD for Rancher Kubernetes"
        tag: "kubernetes"
        url: "https://argocd.roonaldo.org/"
      - name: "InfluxDB"
        logo: "assets/tools/png/influxdb.png"
        subtitle: "influxdb for Rancher Kubernetes"
        tag: "kubernetes"
        url: "http://pc.sandstorm.iot:8086/signin"

  #Portainer services
  - name: "Portainer"
    icon: "fas fa-cloud"
    logo: "assets/tools/png/portainer.png"
    items:
      - name: "Portainer"
        logo: "assets/tools/png/portainer.png"
        subtitle: "Portainer"
        tag: "Portainer"
        url: "https://pc.sandstorm.iot:9443/"
      - name: "BlueIris"
        logo: "assets/tools/png/portainer.png"
        subtitle: "Blue Iris System"
        tag: "Portainer"
        url: "http://blue.sanstorm.home:81/"
      - name: "Uptime Kuma"
        logo: "assets/tools/png/portainer.png"
        subtitle: "Uptime Kuma"
        tag: "Portainer"
        url: "http://pc.sandstorm.iot:3001/dashboard"

  #Ping services
  - name: "Ping"
    icon: "fas fa-cloud"
    logo: "assets/tools/png/ping.png"
    items:
      - name: "PingDirectory"
        logo: "assets/tools/png/ping.png"
        subtitle: "Ping Directory LDAP"
        tag: "Ping"
        url: "https://pingds.ping.net:8443/console/login"
      - name: "Ping Delegator"
        logo: "assets/tools/png/ping.png"
        subtitle: "Ping Delegator"
        tag: "Ping"
        url: "https://pingds.ping.net:8443/delegator"
      - name: "Ping Federate"
        logo: "assets/tools/png/ping.png"
        subtitle: "Ping Federate"
        tag: "Ping"
        url: "https://pingfed.ping.net:9999/"

  #Home
  - name: "Home"
    icon: "fas fa-cloud"
    items:
      - name: "qBittorrent Web UI"
        logo: "assets/tools/png/qbittorrent.png"
        subtitle: "Tor Downloader"
        tag: "tor"
        url: "http://toro.sandstorm.iot:9090/"
      - name: "Radarr"
        logo: "assets/tools/png/radarr.png"
        subtitle: "Radarr App"
        tag: "tor"
        url: "http://toro.sandstorm.iot:7878/"
      - name: "Sonarr"
        logo: "assets/tools/png/sonarr.png"
        subtitle: "Sonarr"
        tag: "tor"
        url: "http://toro.sandstorm.iot:8989/"
      - name: "Plex"
        logo: "assets/tools/png/plex.png"
        subtitle: "Plex Server"
        tag: "tor"
        url: "http://plex.sandstorm.iot:32400/"
      - name: "ProxMox"
        logo: "assets/tools/png/proxmox.png"
        subtitle: "Home Lab"
        tag: "home"
        url: "https://prox.sandstorm.home:8006/"
      - name: "Jackett"
        logo: "assets/tools/png/jackett.png"
        subtitle: "Api client"
        tag: "tor"
        url: "http://toro.sandstorm.iot:9117/UI/Dashboard"
      - name: "Unifi"
        logo: "assets/tools/png/unifi.png"
        subtitle: "Home networking"
        tag: "home"
        url: "https://unifi/"
      - name: "PiHole"
        logo: "assets/tools/png/pihole.png"
        subtitle: "DNS services"
        tag: "home"
        url: "http://raspi3.sandstorm.iot/admin"
      - name: "HomeAssistant"
        logo: "assets/tools/png/home-assistant.png"
        subtitle: "Home Automations for the soul"
        tag: "home"
        url: "https://roonaldo.duckdns.org:8123/lovelace/home"
      - name: "OctoPrint"
        logo: "assets/tools/png/octoprint.png"
        subtitle: "Home Automations for the soul"
        tag: "home"
        url: "http://octopi.sandstorm.iot/"
      # - name: "HomeAssistant"
      #   logo: "assets/tools/png/home-assistant.png"
      #   subtitle: "Sample"
      #   tag: "home"
      #   url: "https://roonaldo.duckdns.org:8123/lovelace/home"
