apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: homer-server
  namespace: homer
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`homer.roonaldo.org`)
      priority: 10
      services:
        - name: homer-server
          port: 8080
    - kind: Rule
      match: Host(`homer.roonaldo.org`) && Headers(`Content-Type`, `application/grpc`)
      priority: 11
      services:
        - name: homer-server
          port: 8080
          scheme: h2c
  tls:
    secretName: homer-tls-secret
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homer-cert
  namespace: homer
spec:
  secretName: homer-tls-secret
  issuerRef:
    name: ssl-issuer
    kind: ClusterIssuer
  dnsNames:
    - homer.roonaldo.org
