apiVersion: v1
kind: Service
metadata:
  name: ping-service
spec:
  type: NodePort
  # labels:
  #   app.kubernetes.io/name: pingdatasync
  ports:
    - name: ldaps
      nodePort: 30080
      port: 1636
      targetPort: 1636
  selector:
    app: pingdatasync
    type: ping-service
