apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik
  namespace: traefik
spec:
  secretName: traefik
  issuerRef:
    name: acme-issuer

    kind: ClusterIssuer
  dnsNames:
    - "traefik.roonaldo.org"
