#$ echo 'my-secret-key' | base64 -w0 | sed -e 's/+/-/g' -e 's/\//_/g' -e 's/=//g'

#  kubectl create secret generic eab-secret --from-literal \
#  secret={base64 encoded secret key}
#  kubectl create secret generic eab-secret --from-literal \
#  secret='bXktc2VjcmV0LWtleQo'

#'secretsecret'
#bXktc2VjcmV0LWtleQo

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-issuer
  # (Optional) Metadata
  # ---
  # namespace: cert-manager

spec:
  acme:
    # Configure your email here...
    # ---
    email: nkreadly@gmail.com

    # Configure your server here...
    # ---
    # Letsencrypt Production
    server: https://acme-v02.api.letsencrypt.org/directory
    # - or -
    # Letsencrypt Staging
    # server: https://acme-staging-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: example-issuer-account-key
    solvers:
      # Configure DNS or HTTP Challenge here...
      # ---
      # DNS Challenge:
      - dns01:
          # Configure your DNS Provider here...
          # ---
          cloudflare:
            email: nkreadly@gmail.com
            # API Key:
            apiKeySecretRef:
              name: cloudflare-api-key-secret
              key: api-key
          # - or -
          # API Token:
          #   apiTokenSecretRef:
          #     name: cloudflare-api-token-secret
          #     key: api-token
        # (Optional) Add DNS selectors
        # ---
        # selector:
        #   dnsNames:
        #     - "roonaldo.org"
        #     - "*.roonaldo.org"

    # HTTP Challenge:
    # - http01:
    #    ingress:
    #      class: traefik
