apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-test
  namespace: nginx-test
spec:
  secretName: nginx-test
  issuerRef:
    name: acme-issuer

    kind: ClusterIssuer
  dnsNames:
    - "nginx-test.roonaldo.org"
